### ISSUE TITLE
image not found

### ISSUE THREAD

**Issue by ghondar** [jaruba/node-vlcPlayer-demo#1]
I'm using osx 10.10.3 Yosemite, and I'm having trouble nw, and electron when running the program
also i make the installation of https://github.com/RSATom/WebChimera.js

[19683:0621/023319:INFO:CONSOLE(83)] "Uncaught Error: dlopen(/Users/trabajo/Documents/webchimeraplayer/node-vlcPlayer-demo/node_modules/wcjs-player/node_modules/wcjs-renderer/node_modules/webchimera.js/build/Release/WebChimera.js.node, 1): Library not loaded: @loader_path/lib/libvlc.5.dylib
  Referenced from: /Users/trabajo/Documents/webchimeraplayer/node-vlcPlayer-demo/node_modules/wcjs-player/node_modules/wcjs-renderer/node_modules/webchimera.js/build/Release/WebChimera.js.node
  Reason: image not found", source: /Users/trabajo/Documents/webchimeraplayer/node-vlcPlayer-demo/node_modules/wcjs-player/node_modules/wcjs-renderer/node_modules/webchimera.js/node_modules/bindings/bindings.js (83)

**Comment by jaruba** [comment]
> image not found

very strange.. the player does not contain any images, could you please be a bit more specific about how the demo reacts? Do you get any error in the javascript console?

**Comment by jaruba** [comment]
it does not seem to be a error with the demo itself, the issue is most probably with how you embedded `VLC`, I know there are some issues with embedding the latest version of `VLC` in `WebChimera.js` on Mac

@Ivshti @RSATom do you guys know how to fix this?

**Comment by RSATom** [comment]
@abgv9221, you should place `libvlc` (and all related files) near the `WebChimera.js.node` to the `lib` folder

**Comment by ghondar** [comment]
thanks guys for your quick response, a version of libvlc in specific?

**Comment by RSATom** [comment]
it was tested with vlc 2.1.x and vlc 2.2.x ( but to use second one on Mac you will have to use some hack: https://github.com/RSATom/WebChimera.js/releases/download/v.0.1.3/libvlc_2.2.1_mac.zip )

**Comment by RSATom** [comment]
but I think it could be used with older version too

**Comment by Ivshti** [comment]
Unzip RSATom's link where WebChimera.js.node is. But the trick here is that, under yosemite with electron at least, I think require-ing webchimera.js directly doesn't work and you **have to point to the full path to WebChimera.js.node**.

**Comment by ghondar** [comment]
Hello everyone: D, I hit the lib folder alongside WebChimera.js.node

http://fotos.subefotos.com/a15641d79c1546f58861a2e1a5ba4390o.png

but now I get this error:

[19987:0621/091935:INFO:CONSOLE(83)] "Uncaught Error: Module version mismatch. Expected 43, got 44.", source: /Users/trabajo/Documents/webchimeraplayer/node-vlcPlayer-demo/node_modules/wcjs-player/node_modules/wcjs-renderer/node_modules/webchimera.js/node_modules/bindings/bindings.js (83)

**Comment by RSATom** [comment]
@abgv9221, you need install latest `Electron` (it seems you have 0.27, latest is 0.28)

**Comment by ghondar** [comment]
RSATom thanks, now works perfectly in electron, but nwjs v0.12.2, the same error keeps coming

http://fotos.subefotos.com/b9bd8a82b2dfa5b0ebd87c3825e8e133o.png

**Comment by RSATom** [comment]
if you first build it for electron, and now want use with `nw.js` you have to force rebuild `WebChimera.js`.

**Comment by ghondar** [comment]
good point, and now I work in nw.js too, thanks for your time: D

**Comment by RSATom** [comment]
You are welcome! :) I hope it will be useful to you.
