### ISSUE TITLE
Not working with nw.js v0.16.1

### ISSUE THREAD

**Issue by hlgkb** [jaruba/node-vlcPlayer-demo#13]
I cloned this files and installed "wcjs-player"  and "wcjs-prebuilt" as mention on the instruction. And I opened it using nw.js v16.1 x64 all I got was a blank window.

![iss](https://cloud.githubusercontent.com/assets/9023528/18504088/28462368-7a80-11e6-8720-4e4418779b95.PNG)

There was a error in console saying `E:\tries\node-vlcPlayer-demo\node_modules\wcjs-player\index.js:41 Uncaught TypeError: Cannot read property 'addRule' of undefined`

![err](https://cloud.githubusercontent.com/assets/9023528/18504156/953bf434-7a80-11e6-9833-5899f315cbf1.PNG)

How do I make this thing work?

**Comment by jaruba** [comment]
https://github.com/RSATom/WebChimera.js/wiki/Latest-Electron-and-NW.js-versions-has-compatibility-issue-on-Windows

**Comment by hlgkb** [comment]
I did set the VLC_PLUGIN_PATH environment variable before opening NW.js using bat file as mention in this [issue](https://github.com/RSATom/WebChimera.js/issues/73) still got the same error. I also tried placing path to libvlc.dll to PATH env variable that worked.

**Comment by RSATom** [comment]
@hlgkb, then please download https://technet.microsoft.com/en-us/sysinternals/debugview.aspx and look debug log there.

**Comment by hlgkb** [comment]
@RSATom , As you said I downloaded the DebugView and looked into the log. Only log captured while running NW.js was   `[4896] install_static::'anonymous-namespace'::RecursiveDirectoryCreate( C:\Users\lenovo\AppData\Local\Chromium\User Data directory exists )`

**Comment by RSATom** [comment]
Since you don't have any messages related to libvlc there, I think it not loading at all.
Possible reasons:
a) you placed it to wrong place
b) you use 32-bit libvlc with 64-bit NW.js or vice versa
c) maybe something else, don't sure yet...

**Comment by hlgkb** [comment]
Version of NW.js I used is v0.16.1-sdk-ia32 and the prebuilt that I used is WebChimera.js_v0.2.6_nw_v0.16.1_VLC_v2.2.4_ia32_win. Don't know what is wrong.

**Comment by RSATom** [comment]
Where did you extract WebChimera.js_v0.2.6_nw_v0.16.1_VLC_v2.2.4_ia32_win.zip?

**Comment by hlgkb** [comment]
I extracted it in **node_modules\wcjs-prebuilt\bin**

![capture](https://cloud.githubusercontent.com/assets/9023528/18605707/12635774-7cb9-11e6-975e-eb40cf7b7c6c.PNG)

**Comment by RSATom** [comment]
try place it to `node_modules\wcjs-prebuilt`

**Comment by hlgkb** [comment]
I did but still not working.  Still same error :(

**Comment by RSATom** [comment]
something in DebugView?

**Comment by hlgkb** [comment]
Same log as before.

**Comment by RSATom** [comment]
Then I whould recommend you get https://github.com/RSATom/wcjs-ugly-demo working first.

**Comment by hlgkb** [comment]
Okay I will. I was thinking of creating a repository with all files I used. Will you take a time to look at it so you might figure out what went wrong actually?

**Comment by hlgkb** [comment]
@jaruba @RSATom  can you help  me? I am getting error saying **Uncaught TypeError: Cannot read property 'addRule' of undefined** at line 41 of "**wcjs-player\index.js**". Then I tried to require both modules in console of nwjs. I got error saying **D:\Cloned\node-vlcPlayer-demo\node_modules\wcjs-player\index.js:81 Uncaught TypeError: Cannot read property 'firstChild' of null at new wjs (D:\Cloned\node-vlcPlayer-demo\node_modules\wcjs-player\index.js:81:70)**

I am using nwjs v17.1x64 and wcjs-prebuilt v0.2.6.
![untitled00](https://cloud.githubusercontent.com/assets/9023528/22645868/5ef85d08-ec91-11e6-92ea-1d43542c9d3c.png)

**Comment by RSATom** [comment]
Did you get `wcjs-ugly-demo` working?

**Comment by hlgkb** [comment]
I got no error in console but couldn't get the video to play.  I got this on **[3312] core libvlc error: No plugins found! Check your VLC installation.** debug view. As told in [readme](https://github.com/RSATom/wcjs-ugly-demo) I cloned the `wcjs-ugly-demo` repo and did `npm install --ignore-scripts` then extracted **WebChimera.js_v0.2.6_nw_v0.16.1_VLC_v2.2.4_ia32_win** to **node_modules**

**Comment by RSATom** [comment]
You should read this: https://github.com/RSATom/WebChimera.js/wiki/Latest-Electron-and-NW.js-versions-has-compatibility-issue-on-Windows

**Comment by hlgkb** [comment]
I have read it many time. Tried all option mention there. But still it's not working. I am suppose to extract **WebChimera.js_v0.2.6_nw_v0.16.1_VLC_v2.2.4_ia32_win.zip** directly in **node_modules** where it already contains folder with name **webchimera.js**.

**Comment by RSATom** [comment]
Since you've got `core libvlc error: No plugins found! Check your VLC installation` message - it means you have libvlc installed correctly. All you need to do to get it working, you need set `VLC_PLUGIN_PATH` environment variable to valid path to libvlc plugins before run your application. You have some options how exactly to do it, one of them just create .cmd in which set `VLC_PLUGIN_PATH` first, and run Nw.js second.

**Comment by hlgkb** [comment]
Thank you @RSATom. You have mention following code in [issue 73](https://github.com/RSATom/WebChimera.js/issues/73#217483408) of WebChimera.js.

```
@echo off

for %%i in ("%~0") do set THIS_BAT_PATH=%%~dpi
set VLC_PLUGIN_PATH=%THIS_BAT_PATH%\node_modules\webchimera.js\build\Release\plugins

nw .

```

There was problem with one backslash present in `%THIS_BAT_PATH%\node_modules` I changed the code to following and it worked.

```
@echo off

for %%i in ("%~0") do set THIS_BAT_PATH=%%~dpi
set VLC_PLUGIN_PATH=%THIS_BAT_PATH%node_modules\webchimera.js\build\Release\plugins

nw .

```
