### ISSUE TITLE
Module version mismatch: Expected 44, got 43.

### ISSUE THREAD

**Issue by ghost** [jaruba/node-vlcPlayer-demo#2]
I need help in running the demo

I followed the instructions on https://github.com/jaruba/node-vlcPlayer-demo
- git clone https://github.com/jaruba/node-vlcPlayer-demo.git
- cd node-vlcPlayer-demo
- npm install
- installed electron via "npm install electron-prebuilt --save-dev" . My electron version inside node_modules is "v0.29.2"
- took the vlc lib zip created by RSATom from https://github.com/jaruba/node-vlcPlayer-demo/issues/1#issuecomment-113905284 and placed it next to WebChimera.js.node 

I get the following error
/Users/***/code/node-vlcPlayer-demo/node_modules/wcjs-player/node_modules…s-renderer/node_modules/webchimera.js/node_modules/bindings/bindings.js:83 Uncaught Error: Module version mismatch. Expected 44, got 43.

What step should i check?

**Comment by RSATom** [comment]
use this https://github.com/RSATom/WebChimera.js/blob/master/build_electron.sh to build

**Comment by ghost** [comment]
Building with the build_electron.sh throws the following

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
LIBVLC_LIBRARY
    linked by target "libvlc_wrapper" in directory /Users/**/code/node-vlcPlayer-demo/node_modules/wcjs-player/node_modules/wcjs-renderer/node_modules/webchimera.js/deps/libvlc_wrapper

-- Configuring incomplete, errors occurred!
See also "/Users/**/code/node-vlcPlayer-demo/node_modules/wcjs-player/node_modules/wcjs-renderer/node_modules/webchimera.js/build/CMakeFiles/CMakeOutput.log".
ERR! OMG Process terminated: 1
Unhandled rejection Error: Process terminated: 1
    at ChildProcess.<anonymous> (/Users/**/code/node-vlcPlayer-demo/node_modules/wcjs-player/node_modules/wcjs-renderer/node_modules/webchimera.js/node_modules/cmake-js/lib/cMake.js:366:28)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

Should i point LIBVLC_LIBRARY to the unzipped libvlc that i downloaded from issue#1

**Comment by RSATom** [comment]
You should install `VLC.app` before build to `/Applications`

**Comment by ghost** [comment]
Works. I removed vlc.app while debugging. Hoping to narrow down the issue. Adding VLC 2.2.1 into applications solved the issue.
Thanks RSATom

**Comment by RSATom** [comment]
I'm glad to hear you got it working.

**Comment by heuuLZP** [comment]
Hi guy:  

I have some problems on the platform of win32 .  

The code project  is  in my mac . I  pack a electron.exe ,  then run it on windows .

```
export WCJS_RUNTIME="electron"
export WCJS_RUNTIME_VERSION="v1.4.13"
export WCJS_VERSION="v0.2.7"
export WCJS_ARCH="x64"     //  ia32 is not work, will have a error "!% is not a valid Win32 application"
export WCJS_PLATFORM="win"
```   
electron : v1.4.13
platform : win32   (console.log(process.platform))

![bug](https://cloud.githubusercontent.com/assets/18410118/24028557/facf7a26-0b0a-11e7-87b2-bbd3a03a8256.png)


A week ago , I have the same problem on the platform of macOS  , but I solved according to your answer  .

```
export npm_config_wcjs_runtime="electron"
export npm_config_wcjs_runtime_version="1.4.13"
npm install
```

I also try this methods , but not work .  

Can you help me ?  thank you.   @RSATom

**Comment by RSATom** [comment]
Are you sure use Electron v1.4.13?

**Comment by heuuLZP** [comment]
Yes 。
```
npm uninstall electron  
npm install electron v1.4.13
```

and `npm install wcjs-prebuilt`  

![dc4531c6-a517-4d87-815b-c3e86d4b2964](https://cloud.githubusercontent.com/assets/18410118/24029059/d5ada2a0-0b0e-11e7-93cd-f8c64b6c58d4.png)

**Comment by RSATom** [comment]
check it with `electron --version`

**Comment by heuuLZP** [comment]
oh , sorry , it show v1.6.2
but I install v1.4.13 ,it is why ?

![9dd60b0a-6343-46b5-a52e-aac0633dc302](https://cloud.githubusercontent.com/assets/18410118/24029131/300eb298-0b0f-11e7-8793-c3d8e23a1481.png)

I know  , Global installation electron is v1.6.2 .

**Comment by RSATom** [comment]
Don't know. I've forced binaries rebuild for latest `electron` version. It will be available soon.

**Comment by heuuLZP** [comment]
ok, I will try again .

**Comment by heuuLZP** [comment]
## error
I set up a new project  on platform OSX,  use command  
```
export WCJS_RUNTIME="electron"
export WCJS_RUNTIME_VERSION="v1.4.13"
export WCJS_VERSION="v0.2.7"
export WCJS_ARCH="x64" 
```
It will download  WebChimera.js_v0.2.7_electron_v1.4.`13`_VLC_v2.2.4_x64_osx.tar.gz ,  and the electron version is v1.4.13   

It's show error Node.js version 50 and 53 are against .

## correct
 After many attempts ， I found the  difference between two project . use commond 
```
export WCJS_RUNTIME="electron"
export WCJS_RUNTIME_VERSION="latest"   ## changed
export WCJS_VERSION="latest"           ## changed
export WCJS_ARCH="x64" 
```
It will download  WebChimera.js_v0.2.7_electron_v1.4.`3`_VLC_v2.2.4_x64_osx.tar.gz ,  and the electron version is v1.4.13  . 

It's work ! 

## question
But only work on platform OSX .
The same commond , just change `WCJS-PLATFORM="win"`, can't work on windows . @RSATom

**Comment by RSATom** [comment]
`wcjs-prebuilt` is not mine project, and I don't know internals. It's possible some bug there. Don't know.
