### ISSUE TITLE
Setup Problem

### ISSUE THREAD

**Issue by sphelan-extron** [jaruba/node-vlcPlayer-demo#5]
I'm having a setup problem.  I think I'm having a problem linking the webchimera.js code into the node-vlcPlayer-demo.  I've run the webchimera.js steps with no build problems.  then I ran the node-vlcPlayer-demo steps with no problems.  I copied everything from c:\Program Files (x86)\VideoLAN\VLC into node-vlcPlayer-demo that was created when I did cloned the repo.  Then I copied the files from NW.js in the same node-vlcPlayer-demo folder.  When I try to run nw.exe the page opens, but I get the following errors.

![capture](https://cloud.githubusercontent.com/assets/1561099/9144759/22b9462e-3d1d-11e5-97d6-0d46c214be5e.PNG)

This is windows 8.1, VLC 2.2.1, nw.js 0.12.3.

Thanks for any assistance.

**Comment by jaruba** [comment]
use `NW.js 0.12.2`

**Comment by jaruba** [comment]
To expand on my answer, `WebChimera.js` builds for `NW.js 0.12.2 - 32bit` by default, if you want to build it for `NW.js 0.12.3 - 32bit`, you will need to set build conditions from the command line before doing `npm install`.

Commands:

```
set npm_config_wcjs_runtime="nw"
set npm_config_wcjs_runtime_version="0.12.3"
set npm_config_wcjs_arch="ia32"

npm install
```

**Comment by jaruba** [comment]
You should also make sure that `VLC 2.2.1` is 32bit too.

**Comment by sphelan-extron** [comment]
Thanks I think it was because I was using nw.js 64-bit

**Comment by jaruba** [comment]
makes sense :)

keep in mind that `wcjs-player` (the repo that this demo is actually for) has a [different API](https://github.com/jaruba/wcjs-player/wiki/JavaScript-API) then `wcjs`
