### ISSUE TITLE
Demo is not working Win 10 x64

### ISSUE THREAD

**Issue by devlo** [jaruba/node-vlcPlayer-demo#8]
Reproducing:
1. Git Clone this demo.
2. npm install
3. Download electron 0.37.5 x64
4. Download WebChimera.js_v0.2.3_electron_v0.37.5_VLC_v2.2.2_x64_win.zip
5. Replace Release dir content with extracted WebChimera.js_v0.2.3_electron_v0.37.5_VLC_v2.2.2_x64_win.
6. Launch Electron.
7. Drag app.js from demo dir into electron window.
8. New empty window will open + developer tools which are "disconnected from the page".

**Comment by jaruba** [comment]
Yes, you need to set:

```
if (/^win/.test(process.platform))
    process.env['VLC_PLUGIN_PATH'] = require('path').join(__dirname, '../bin/plugins');
```

^ make sure to change this to the correct path to the `vlc`'s `plugins` folder in your app (should find it in the same folder as `webchimera.js.node`).

You should put these as the very first lines that are run by your app. This is only needed for Electron 0.37+ on Windows.

**Comment by devlo** [comment]
@jaruba 

Thank you! it works.

**Comment by devlo** [comment]
@jaruba 

What about using asar in electron? It dosen't work packed on Windows.

**Comment by jaruba** [comment]
You just need to keep `libVLC` and `WebChimera.js.node` outside the asar, and make sure that the env var is set correctly to the `plugins` path when packed too.

**Comment by devlo** [comment]
I am using wcjs-player, should i change path in it anywhere to WebChimera.js.node?

EDIT: I have changed vlc plugins env and got plugins outside of asar, but what about WebChimera.js.node?

**Comment by jaruba** [comment]
If you know the `WebChimera.js.node`'s location (all the `libVLC` files should be in the same folder too), then move that entire folder to something like `bin/` in the root folder of your app (obviously, outside the asar). Then when starting `wcjs-player` use:

```
var pathToWebChimera = ???;

var wcjsPlayer = require('wcjs-player');
var player = new wjsPlayer("#player").addPlayer({ autoplay: true, wcjs: require(pathToWebChimera) })
```

(where `pathToWebChimera` needs to be the path to `WebChimera.js.node`)

And make sure that the path you set for the `plugins` folder (you'll need to change it now to the new path) with this code:

```
if (/^win/.test(process.platform))
    process.env['VLC_PLUGIN_PATH'] = require('path').join(__dirname, '../bin/plugins');
```

is still correct when your using asar.

**Comment by devlo** [comment]
I am little confused with paths from inside asar file. So if i have path `app` and inside that path i have electron.exe etc and then i have my asar app  `app/resources/app.asar`  and then file from which i launch player is  `app/resources/app.asar/dist/video.html` and i have webchimera.js.node and plugins dir here `app/bin` then path to plugins would be `require('path').join(__dirname, '../../bin/plugins')`  ?

**Comment by jaruba** [comment]
should be, but your missing a `../`, because `app.asar` is considered a folder.

**Comment by devlo** [comment]
ah so `require('path').join(__dirname, '../../../bin/plugins')` right?

**Comment by jaruba** [comment]
hopefully yes, you can do a `console.log(__dirname)` if it doesn't work, to figure out your exact location.

**Comment by devlo** [comment]
Ok, it works. You were very helpful once again, thank you!
