### ISSUE TITLE
Linux Installation for demo

### ISSUE THREAD

**Issue by jhondelbaguio** [jaruba/node-vlcPlayer-demo#9]
OS : Ubuntu 14.04 LTS
NW version : 0.14.3-sdk 

My steps so far.
1. clone this repo.
2. npm install
3. start NW.

now after those process. i got his error
_Cannot read property 'addRule' of undefined
"window.document.styleSheets[0].addRule('........');"_

i already added style tag on my main html.

is there something that i've missed?

**Comment by jaruba** [comment]
If you installed the prerequisites, then no, there should be no issues..

That error is specific to not being able to find a style tag in the header as you suspected, what happens when you do `window.document.styleSheets` in the console?

**Comment by jhondelbaguio** [comment]
Hi Jaruba.

Object found when i do log the "window.document.styleSheets".

just now i added, the css/general.css via link rel on my html file, so that it would not execute the injection of css. and i got another error,

_" Cannot read property 'firstChild' of null
  if (window.document.getElementById(this.context.substring(1)).firstChild) {
"_

**Comment by jaruba** [comment]
Are you using it in a new window instead of the default window that opens when you start the app?

**Comment by jhondelbaguio** [comment]
I'm using it as default window via package.json "main" : "index.html"

**Comment by jaruba** [comment]
well.. it looks like the `window` it's checking, is not the `window` where you want the player to be.

**Comment by jhondelbaguio** [comment]
what do you mean?

here's my index.html

```
<html>
<head>
<style>
body,html{ width: 100%; height: 100%; padding: 0px; margin:0px }
#player { width: 100%; height: 100% }
</style>
</head>
<body>
<div id="player"></div>
<script>

var wjs = require("wcjs-player");
var player = new wjs("#player").addPlayer({ autoplay: true });

player.addPlaylist("http://archive.org/download/CartoonClassics/Krazy_Kat_-_Keeping_Up_With_Krazy.mp4");

</script>
</body>
</html>
```

and my package.json

```
{
    "name": "wcjs-player-demo",
    "description": "WebChimera.js Player Demo",
    "version": "0.0.1",
    "private": true,
    "main": "index.html",
    "dependencies": {
        "wcjs-player": "*"
    },
    "env": "development"
}

```

i also tried this running on windows. still no luck. :(

**Comment by jaruba** [comment]
- Open `node_modules/wcjs-player/index.js`
- Add `win = window` [to the vars](https://github.com/jaruba/wcjs-player/blob/master/index.js#L33)
- Add `win = wcpSettings.win ? wcpSettings.win : window;` right above [this line](https://github.com/jaruba/wcjs-player/blob/master/index.js#L241)
- Replace all `window.` with `win.` in the entire file
- Use `var player = new wjs("#player").addPlayer({ autoplay: true, win: window });` instead of the `addPlayer()` call your doing now

**Comment by jhondelbaguio** [comment]
I followed the instructions above and still got an error about the addRule.

**Comment by jaruba** [comment]
Then try a different version of `NW.js`, this can't be the player's fault, as it couldn't break `window` even if it wanted to.

**Comment by jhondelbaguio** [comment]
Hi Jaruba, 

Its working now, i use the old version of NW.JS (0.12.3).

Thank you so much for your time :)

**Comment by xiongjiabin** [comment]
Not familiar with NW & eletron,
after I build successfully( npm install), how to run the demo?

**Comment by jaruba** [comment]
@xiongjiabin as you created a different issue with a running nw.js or electron, I guess you figured it out, closing as the original issue was solved
